### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by mrjshzk** [bhavyapandya07/Steam-Crack-Mega_Thread#3]
I'd like to see the source code before trying it out.

**Comment by bhavyapandya07** [comment]
@mrjshzk which specific tool you looking for?

**Comment by mrjshzk** [comment]
Both of them

**Comment by bhavyapandya07** [comment]
> Both of them

@mrjshzk its from here [Steam Achivement](https://github.com/gibbed/SteamAchievementManager) & [Steam Farm](https://github.com/JustArchiNET/ArchiSteamFarm)
